version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: twitter_postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d twitter_clone"]
      interval: 10s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitter_backend
    restart: always
    env_file: .env
    environment:
      - APP_ENV=development
      - APP_DEBUG=True
      - BACKEND_PORT=8001
    command: ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8001"]
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8001"            # фронт + API доступны на http://localhost:8001
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./media:/app/media

volumes:
  db_data: